### ISSUE TITLE
heroku labs:enable user-env-compile is deprecated

### ISSUE THREAD

**Issue by awaxman11** [CarlosPlusPlus/swoonatra#13]
![](http://cl.ly/aXlN/Image%202015-04-04%20at%204.59.04%20PM.png)

Looks like this is a default feature now, so can be removed from the readme (see https://github.com/Crowdtilt/CrowdtiltOpen/issues/251)

**Comment by CarlosPlusPlus** [comment]
Deleted from my README file via this commit: d3c5f35688d6034b254650798305d66b1f71eac6.
You totally rock, @awaxman11 - thanks for the heads up! :+1:
