### ISSUE TITLE
foreman is not part of the bundle

### ISSUE THREAD

**Issue by TheSunak** [CarlosPlusPlus/swoonatra#17]
Foreman is not currently included in the Gemfile so this error shows when doing "foreman start".

```$foreman start
/Users/vishal/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': foreman is not part of the bundle. Add it to Gemfile. (Gem::LoadError)```

Adding foreman to the Gemfile/Gemfile.lock fixes this error.

**Comment by CarlosPlusPlus** [comment]
Thanks for bringing this up, @TheSunak. Installing the Heroku CLI should install this automatically as of recently, but I'll add it to the `Gemfile` just to make sure it's available.
