### ISSUE TITLE
Page-Specific Custom CSS Not Being Included in Layout

### ISSUE THREAD

**Issue by TheSunak** [CarlosPlusPlus/swoonatra#4]
There is an issue when trying to include specific custom CSS using the css helper method in head_cleaner.rb file. Need to fix layout.erb to include this by default.

**Comment by CarlosPlusPlus** [comment]
This is awesome, @TheSunak - thanks for pointing this out! Looking and fixing this issue actually led me to doing some rework in how some of these files are compiled, so many thanks! :+1:
